--------------------------------------------------------
--  建立表格
--------------------------------------------------------
alter session set deferred_segment_creation=false;

DROP TABLE FAVORITE_GOODS;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDER_HISTORY;

DROP SEQUENCE ORDER_DETAIL_seq;
DROP SEQUENCE ORDER_HISTORY_seq;

--------------------------------------------------------
--  for Table ORDER_HISTORY 訂單紀錄
--------------------------------------------------------
CREATE TABLE ORDER_HISTORY (
  ORDER_NO			VARCHAR2(14)	NOT NULL, 
  MEMBER_NO	   	 	VARCHAR2(7)		NOT NULL, 
  ORDER_PRICE		NUMBER(10,0)	NOT NULL, 
  PAY_METHODS		VARCHAR2(14)	NOT NULL, 
  SHIPPING_METHODS	VARCHAR2(14)	NOT NULL, 
  ORDER_DATE		TIMESTAMP, 
  ORDER_ETD   		TIMESTAMP, 
  PICKUP_DATE		TIMESTAMP,
  RECEIVER_ADD		VARCHAR2(80),
  RECEIVER_NAME		VARCHAR2(80),
  RECEIVER_TEL		VARCHAR2(10),
  ORDER_STATUS		VARCHAR2(12)		NOT NULL,
--  CONSTRAINT MEMBER_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
  CONSTRAINT ORDER_HISTORY_PK PRIMARY KEY (ORDER_NO)
);
  
CREATE SEQUENCE ORDER_HISTORY_seq
INCREMENT BY 1
START WITH 10001
NOMAXVALUE
NOCYCLE
NOCACHE;

Insert into ORDER_HISTORY (ORDER_NO,MEMBER_NO,ORDER_PRICE,PAY_METHODS,SHIPPING_METHODS,ORDER_DATE,ORDER_ETD,PICKUP_DATE,RECEIVER_ADD,RECEIVER_NAME,RECEIVER_TEL,ORDER_STATUS) 
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_HISTORY_seq.NEXTVAL), 5, '0'),'M000001',45000,'EWALLET','STOREPICKUP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'320桃園市中壢區福德一路177巷60弄2號','Peter','0912345678','COMPLETE4');
Insert into ORDER_HISTORY (ORDER_NO,MEMBER_NO,ORDER_PRICE,PAY_METHODS,SHIPPING_METHODS,ORDER_DATE,ORDER_ETD,PICKUP_DATE,RECEIVER_ADD,RECEIVER_NAME,RECEIVER_TEL,ORDER_STATUS) 
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_HISTORY_seq.NEXTVAL), 5, '0'),'M000002',99990,'CREDITCARD','HOMEDELIVERY',CURRENT_TIMESTAMP,'','','320桃園市中壢區中央路100號','David','0913345678','CANCEL5');
Insert into ORDER_HISTORY (ORDER_NO,MEMBER_NO,ORDER_PRICE,PAY_METHODS,SHIPPING_METHODS,ORDER_DATE,ORDER_ETD,PICKUP_DATE,RECEIVER_ADD,RECEIVER_NAME,RECEIVER_TEL,ORDER_STATUS)
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_HISTORY_seq.NEXTVAL), 5, '0'),'M000003',4000,'CREDITCARD','STOREPICKUP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'320桃園市中壢區中央路102號','Sara','0914345678','COMPLETE4');

--------------------------------------------------------
--  for Table ORDER_DETAIL 訂單明細
--------------------------------------------------------
CREATE TABLE ORDER_DETAIL (
  ORDER_NO		VARCHAR2(14)	NOT NULL, 
  GOODS_NO		VARCHAR2(6)		NOT NULL, 
  GOODS_BONUS	NUMBER(10,0),
  GOODS_PC		NUMBER(10,0),
--  CONSTRAINT ORDER_DETAIL_FK1 FOREIGN KEY (ORDER_NO) REFERENCES ORDER_HISTORY (ORDER_NO),
--  CONSTRAINT ORDER_DETAIL_FK2 FOREIGN KEY (GOODS_NO) REFERENCES GOODS (GOODS_NO),
  CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_NO,GOODS_NO)
);

CREATE SEQUENCE ORDER_DETAIL_seq
INCREMENT BY 1
START WITH 10001
NOMAXVALUE
NOCYCLE
NOCACHE;

Insert into ORDER_DETAIL (ORDER_NO,GOODS_NO,GOODS_BONUS,GOODS_PC) 
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_DETAIL_seq.NEXTVAL), 5, '0'),'P10001',15000,3);
Insert into ORDER_DETAIL (ORDER_NO,GOODS_NO,GOODS_BONUS,GOODS_PC) 
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_DETAIL_seq.NEXTVAL), 5, '0'),'P10002',9999,10);
Insert into ORDER_DETAIL (ORDER_NO,GOODS_NO,GOODS_BONUS,GOODS_PC) 
	values ('O'||to_char(sysdate,'yyyymmdd')||LPAD(to_char(ORDER_DETAIL_seq.NEXTVAL), 5, '0'),'P10003',4000,1);

--------------------------------------------------------
--  for Table FAVORITE_GOODS 最愛商品
--------------------------------------------------------
CREATE TABLE FAVORITE_GOODS (	
  MEMBER_NO		VARCHAR2(7)	NOT NULL, 
  GOODS_NO		VARCHAR2(6)	NOT NULL,
--  CONSTRAINT MEMBER_FK1 FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
--  CONSTRAINT GOODS_FK2 FOREIGN KEY (GOODS_NO) REFERENCES GOODS (GOODS_NO),
  CONSTRAINT FAVORITE_GOODS_PK PRIMARY KEY (MEMBER_NO,GOODS_NO)
);

Insert into FAVORITE_GOODS (MEMBER_NO,GOODS_NO) values ('M000001','P10001');
Insert into FAVORITE_GOODS (MEMBER_NO,GOODS_NO) values ('M000002','P10002');
Insert into FAVORITE_GOODS (MEMBER_NO,GOODS_NO) values ('M000003','P10003');
   
commit;